name: moneyball
source: https://storage.cloud.google.com/moneyball/baseball.csv?folder&organizationId=465405141758&_ga=2.120546504.-1320989109.1554983622
target: RS
exclude: Team,League,Year
budget: 3600
providers: google, azure 

